"""Contract digests, computed from the wire models rather than recorded.

A matching protocol version says both sides speak the same *shape* of
conversation. It says nothing about whether they agree on what is in it — the
engine adds a field, the Host keeps compiling, and the mismatch first appears
as a value that is quietly ``undefined`` in production.

Digests close that. Each family's JSON Schema is canonicalised and hashed
here, at import, from the models in :mod:`watch_skill.surfaces.bridge.wire`.
The Host holds the same values as constants and compares them on connect, so a
family that disagrees disables exactly the capabilities that read it and names
both sides.

Computing rather than recording matters: a hardcoded digest is a claim about
the models that nothing checks, and it would keep matching after the models
moved. This one cannot.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any

from watch_skill.surfaces.bridge.wire import FAMILIES

#: Hex characters kept from each sha-256. Sixteen bytes is far past collision
#: risk for six families, and matches the width every recorded digest already
#: uses — widening it would be a breaking change for no gain.
_DIGEST_HEX = 32


def canonical_json(payload: Any) -> bytes:
    """Serialize so that only a *meaningful* change moves the bytes.

    Keys are sorted and separators are fixed, so a reordered field does not
    read as a breaking change while a renamed one does.
    """
    return json.dumps(
        payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    ).encode("utf-8")


def digest_of(schema: dict[str, Any]) -> str:
    """The ``sha256:<32 hex>`` digest of one canonicalised schema."""
    return "sha256:" + hashlib.sha256(canonical_json(schema)).hexdigest()[:_DIGEST_HEX]


def family_schemas() -> dict[str, dict[str, Any]]:
    """JSON Schema for every contract family, keyed by family name.

    Serialization mode is used because that is what actually crosses the wire:
    a validation-mode schema would describe what Core accepts, and the Host
    consumes what Core emits.
    """
    return {
        name: model.model_json_schema(by_alias=True, mode="serialization")
        for name, model in FAMILIES.items()
    }


def schema_digests() -> dict[str, str]:
    """The digest per family, as the handshake reports it."""
    return {name: digest_of(schema) for name, schema in family_schemas().items()}


def manifest() -> dict[str, Any]:
    """The full generated manifest: schemas plus their digests.

    Written to ``schemas/bridge/manifest.json`` by
    ``scripts/gen_bridge_schemas.py`` and checked for freshness in CI, so a
    model change that is not regenerated fails the build rather than shipping
    a manifest that describes the previous release.
    """
    from watch_skill.surfaces.bridge.protocol import (
        PROTOCOL_VERSION,
        PROTOCOL_VERSION_MIN,
    )

    schemas = family_schemas()
    return {
        "$comment": (
            "Generated by scripts/gen_bridge_schemas.py from "
            "watch_skill.surfaces.bridge.wire. Do not edit by hand."
        ),
        "protocolVersion": PROTOCOL_VERSION,
        "protocolMin": PROTOCOL_VERSION_MIN,
        "families": {
            name: {"digest": digest_of(schema), "schema": schema}
            for name, schema in sorted(schemas.items())
        },
    }


#: Digests for this build, computed once at import.
EXPECTED_SCHEMA_DIGESTS: dict[str, str] = schema_digests()

__all__ = [
    "EXPECTED_SCHEMA_DIGESTS",
    "canonical_json",
    "digest_of",
    "family_schemas",
    "manifest",
    "schema_digests",
]
