"""Shared fixtures: every test runs against an isolated data dir WITH SPACES
in its path (both this repo and the reference live in space-containing
directories — treating that as a permanent test case)."""
from __future__ import annotations

from pathlib import Path

import pytest

from watch_skill.config import reset_settings

_AMBIENT_KEYS = (
    "WATCHSKILL_ANTHROPIC_API_KEY",
    "WATCHSKILL_OPENAI_API_KEY",
    "WATCHSKILL_GEMINI_API_KEY",
    "WATCHSKILL_GROQ_API_KEY",
    "WATCHSKILL_OPENROUTER_API_KEY",
    "WATCHSKILL_BIN_DIR",
    "WATCHSKILL_DATA_DIR",
)


@pytest.fixture(autouse=True)
def isolated_settings(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Point Watch Skill at a throwaway data dir (with spaces) for every test."""
    for var in _AMBIENT_KEYS:
        monkeypatch.delenv(var, raising=False)
    data_dir = tmp_path / "agent vision data"
    monkeypatch.setenv("WATCHSKILL_DATA_DIR", str(data_dir))
    # Tests must NEVER reach a live vision backend, and must not inherit a
    # developer's .env vision tuning: `watch-skill setup-vision` writes the
    # chosen model + batch size + num_ctx into the repo .env, which pydantic
    # reads from CWD and would otherwise leak into tests (a moondream .env set
    # WATCHSKILL_VISION_BATCH_SIZE=1 and broke the numbered-describe test).
    # env vars win over .env, so pin every vision knob back to its default.
    monkeypatch.setenv("WATCHSKILL_VISION_CHEAP_PROVIDER", "anthropic")
    monkeypatch.setenv("WATCHSKILL_VISION_STRONG_PROVIDER", "anthropic")
    monkeypatch.setenv("WATCHSKILL_VISION_CHEAP_MODEL", "claude-haiku-4-5-20251001")
    monkeypatch.setenv("WATCHSKILL_VISION_STRONG_MODEL", "claude-sonnet-5")
    monkeypatch.setenv("WATCHSKILL_VISION_BATCH_SIZE", "8")
    monkeypatch.setenv("WATCHSKILL_OLLAMA_NUM_CTX", "2048")
    monkeypatch.setenv("WATCHSKILL_OLLAMA_BASE_URL", "http://127.0.0.1:11434")
    reset_settings()
    yield data_dir
    reset_settings()


@pytest.fixture(scope="session")
def sample_video(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A synthesized 12 s clip with 3 distinct scenes and a 440 Hz tone.

    Generated by ffmpeg lavfi — no copyrighted media in the repo, no network.
    Lives in a directory with spaces (permanent path-handling test case).
    """
    import shutil
    import subprocess

    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        pytest.skip("ffmpeg not available")
    out_dir = tmp_path_factory.mktemp("sample media dir")
    dest = out_dir / "sample clip.mp4"
    cmd = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-y",
        "-f", "lavfi", "-i", "color=c=red:s=320x240:d=4:r=30",
        "-f", "lavfi", "-i", "smptebars=s=320x240:d=4:r=30",
        "-f", "lavfi", "-i", "testsrc2=s=320x240:d=4:r=30",
        "-f", "lavfi", "-i", "sine=f=440:d=12",
        "-filter_complex", "[0:v][1:v][2:v]concat=n=3:v=1[v]",
        "-map", "[v]", "-map", "3:a",
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest",
        str(dest),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        pytest.skip(f"could not synthesize sample clip: {result.stderr[-300:]}")
    return dest
