"""Shared fixtures: every test runs against an isolated data dir WITH SPACES
in its path (both this repo and the reference live in space-containing
directories — treating that as a permanent test case)."""
from __future__ import annotations

from pathlib import Path

import pytest
from agentvision.config import reset_settings

_AMBIENT_KEYS = (
    "AGENTVISION_ANTHROPIC_API_KEY",
    "AGENTVISION_OPENAI_API_KEY",
    "AGENTVISION_GEMINI_API_KEY",
    "AGENTVISION_GROQ_API_KEY",
    "AGENTVISION_OPENROUTER_API_KEY",
    "AGENTVISION_BIN_DIR",
    "AGENTVISION_DATA_DIR",
)


@pytest.fixture(autouse=True)
def isolated_settings(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Point AgentVision at a throwaway data dir (with spaces) for every test."""
    for var in _AMBIENT_KEYS:
        monkeypatch.delenv(var, raising=False)
    data_dir = tmp_path / "agent vision data"
    monkeypatch.setenv("AGENTVISION_DATA_DIR", str(data_dir))
    # Tests must NEVER reach a live vision backend: a developer's .env may
    # point at a reachable local Ollama (this bit us — the API test sat in
    # real CPU inference). Keyless cloud providers fail fast and structured.
    monkeypatch.setenv("AGENTVISION_VISION_CHEAP_PROVIDER", "anthropic")
    monkeypatch.setenv("AGENTVISION_VISION_STRONG_PROVIDER", "anthropic")
    reset_settings()
    yield data_dir
    reset_settings()


@pytest.fixture(scope="session")
def sample_video(tmp_path_factory: pytest.TempPathFactory) -> Path:
    """A synthesized 12 s clip with 3 distinct scenes and a 440 Hz tone.

    Generated by ffmpeg lavfi — no copyrighted media in the repo, no network.
    Lives in a directory with spaces (permanent path-handling test case).
    """
    import shutil
    import subprocess

    ffmpeg = shutil.which("ffmpeg")
    if ffmpeg is None:
        pytest.skip("ffmpeg not available")
    out_dir = tmp_path_factory.mktemp("sample media dir")
    dest = out_dir / "sample clip.mp4"
    cmd = [
        ffmpeg, "-hide_banner", "-loglevel", "error", "-y",
        "-f", "lavfi", "-i", "color=c=red:s=320x240:d=4:r=30",
        "-f", "lavfi", "-i", "smptebars=s=320x240:d=4:r=30",
        "-f", "lavfi", "-i", "testsrc2=s=320x240:d=4:r=30",
        "-f", "lavfi", "-i", "sine=f=440:d=12",
        "-filter_complex", "[0:v][1:v][2:v]concat=n=3:v=1[v]",
        "-map", "[v]", "-map", "3:a",
        "-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest",
        str(dest),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        pytest.skip(f"could not synthesize sample clip: {result.stderr[-300:]}")
    return dest
