/**
 * What OCR actually measured on this machine.
 *
 * Generated by `scripts/ocr-benchmark.mjs` from a real run over a versioned
 * ground-truth corpus. Do not edit: a number typed into a component is a
 * number nobody measured.
 *
 * @module @deepwatch/dsh-client-settings/ocr-measured
 */

/** One workload tier, with the numbers the run produced. */
export interface MeasuredWorkload {
  readonly workload: string
  readonly samples: number
  readonly cer: number
  readonly wordAccuracy: number
  readonly hallucination: number
  /** Against thresholds committed before the benchmark existed. */
  readonly passes: boolean
}

/** Whether any engine has been measured here at all. */
export const OCR_MEASURED = true

/** The engine that was run, and where. */
export const OCR_ENGINE = "rapidocr"
export const OCR_DEVICE = "cpu"

/** Per workload, because qualification is per workload and not an average. */
export const OCR_BY_WORKLOAD: readonly MeasuredWorkload[] = [
  {
    "workload": "dark_mode",
    "samples": 1,
    "cer": 0,
    "wordAccuracy": 1,
    "hallucination": 0,
    "passes": true
  },
  {
    "workload": "document",
    "samples": 1,
    "cer": 0,
    "wordAccuracy": 1,
    "hallucination": 0,
    "passes": true
  },
  {
    "workload": "low_resolution",
    "samples": 4,
    "cer": 0.6111,
    "wordAccuracy": 0.25,
    "hallucination": 0.25,
    "passes": false
  },
  {
    "workload": "mixed_script",
    "samples": 2,
    "cer": 0.75,
    "wordAccuracy": 0.25,
    "hallucination": 0,
    "passes": false
  },
  {
    "workload": "ui_text",
    "samples": 8,
    "cer": 0.0074,
    "wordAccuracy": 0.9792,
    "hallucination": 0,
    "passes": true
  },
  {
    "workload": "video_overlay",
    "samples": 1,
    "cer": 0,
    "wordAccuracy": 1,
    "hallucination": 0,
    "passes": true
  }
]
