/**
 * What the pinned DSH provider catalogue contains.
 *
 * Generated by `scripts/gen-provider-inventory.mjs` from
 * `@earendil-works/pi-ai`. Do not edit: the catalogue is the source of
 * truth and this is a count of it.
 *
 * @module @deepwatch/dsh-client-settings/providers
 */

/** Every provider route the pinned DSH ships. */
export const PROVIDER_COUNT = 37

/** Routes you reach over a network somebody else runs. */
export const HOSTED_COUNT = 30

/**
 * Routes where you supply the endpoint.
 *
 * This is the same mechanism a local model uses: an OpenAI-compatible
 * server on your own machine — Ollama, vLLM, LM Studio, llama.cpp — is a
 * base URL you provide, not a separate feature.
 */
export const SELF_HOSTED_COUNT = 7

/** Whether DeepSeek is one route among many rather than the only one. */
export const DEEPSEEK_IS_OPTIONAL = true

/** A few recognisable names, for a sentence that has to stay short. */
export const SAMPLE_PROVIDERS = ["amazon-bedrock","anthropic","deepseek","google","groq","mistral","openai","openrouter"]
