#!/usr/bin/env node
/**
 * Render the human-readable implementation status from the machine-readable one.
 *
 * There is one source of truth — `docs/implementation-status.json` — and the
 * Markdown is generated from it. A hand-maintained second copy would drift,
 * and a status report that drifts is worse than none: it is a claim nobody
 * checked.
 *
 * The status vocabulary is deliberately strict:
 *
 *   not_started        nothing exists
 *   in_progress        partial, and known to be partial
 *   implemented        real behavior exists — not "a package exists"
 *   tested             its gate actually passed
 *   blocked            cannot proceed without something external
 *   deferred_by_spec   the governing document puts it out of this scope
 *
 * `implemented` is the line people are tempted to cross early. A package with
 * types and no behavior is `in_progress`.
 *
 * Usage:
 *   node scripts/gen-status.mjs          write docs/implementation-status.md
 *   node scripts/gen-status.mjs --check  fail if it is stale
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SOURCE = join(ROOT, 'docs', 'implementation-status.json')
const OUTPUT = join(ROOT, 'docs', 'implementation-status.md')

const VALID_STATUS = new Set([
  'not_started', 'in_progress', 'implemented', 'tested', 'blocked', 'deferred_by_spec',
])

const VALID_CLASSIFICATION = new Set([
  'DSH_EXISTING', 'DSH_EXTENDED', 'WATCH_EXISTING', 'WATCH_NEW', 'DEFERRED',
])

/** How each status is shown, so a skim reads the same as a careful read. */
const MARK = {
  tested: '✅ tested',
  implemented: '🟩 implemented',
  in_progress: '🟨 in progress',
  blocked: '🟥 blocked',
  not_started: '⬜ not started',
  deferred_by_spec: '⏸️ deferred by spec',
}

function main() {
  const check = process.argv.includes('--check')
  const ledger = JSON.parse(readFileSync(SOURCE, 'utf8'))
  const problems = []

  const seen = new Set()
  for (const item of ledger.items) {
    if (seen.has(item.id)) problems.push(`duplicate id: ${item.id}`)
    seen.add(item.id)
    if (!VALID_STATUS.has(item.status)) {
      problems.push(`${item.id}: invalid status ${JSON.stringify(item.status)}`)
    }
    if (!VALID_CLASSIFICATION.has(item.classification)) {
      problems.push(`${item.id}: invalid classification ${JSON.stringify(item.classification)}`)
    }
    // The rule that keeps this honest: a claim of "tested" has to name the
    // test, and a claim of "implemented" has to name the code.
    if (item.status === 'tested' && (item.tests ?? []).length === 0) {
      problems.push(`${item.id}: claims tested but names no test`)
    }
    if ((item.status === 'implemented' || item.status === 'tested')
      && (item.source_paths ?? []).length === 0) {
      problems.push(`${item.id}: claims ${item.status} but names no source`)
    }
    if (item.status === 'blocked' && (item.known_limitations ?? []).length === 0) {
      problems.push(`${item.id}: claims blocked but says nothing about why`)
    }
    for (const path of item.source_paths ?? []) {
      if (!existsSync(join(ROOT, path)) && !existsSync(path)) {
        problems.push(`${item.id}: source path does not exist: ${path}`)
      }
    }
    for (const path of item.tests ?? []) {
      if (!existsSync(join(ROOT, path)) && !existsSync(path)) {
        problems.push(`${item.id}: test path does not exist: ${path}`)
      }
    }
  }

  if (problems.length > 0) {
    for (const problem of problems) process.stderr.write(`watch: ${problem}\n`)
    process.stderr.write(`\nwatch: ${problems.length} ledger problem(s)\n`)
    process.exit(1)
  }

  const counts = {}
  for (const item of ledger.items) counts[item.status] = (counts[item.status] ?? 0) + 1

  const phases = [...new Set(ledger.items.map(item => item.phase))].sort()
  const lines = [
    '# Implementation status',
    '',
    '_Generated from [`implementation-status.json`](implementation-status.json) by',
    '`scripts/gen-status.mjs`. Do not edit this file._',
    '',
    `Baseline: DeepSeek Harness \`${ledger.baseline.dsh}\`, Watch Core \`${ledger.baseline.watchCore}\`.`,
    '',
    '## Where things stand',
    '',
    '| Status | Count |',
    '|---|---:|',
    ...Object.keys(MARK)
      .filter(status => counts[status] !== undefined)
      .map(status => `| ${MARK[status]} | ${counts[status]} |`),
    `| **total** | **${ledger.items.length}** |`,
    '',
    '`implemented` means real behavior exists, not that a package does.',
    '`tested` means the named gate actually passed.',
    '',
  ]

  for (const phase of phases) {
    const items = ledger.items.filter(item => item.phase === phase)
    lines.push(`## ${phase}`, '')
    lines.push('| Subsystem | Status | Owner | Tests |', '|---|---|---|---|')
    for (const item of items.sort((a, b) => a.id.localeCompare(b.id))) {
      const tests = (item.tests ?? []).length === 0
        ? '—'
        : `${String((item.tests ?? []).length)}`
      lines.push(`| \`${item.id}\` — ${item.title} | ${MARK[item.status]} | ${item.owner} | ${tests} |`)
    }
    lines.push('')

    const limited = items.filter(item => (item.known_limitations ?? []).length > 0)
    if (limited.length > 0) {
      lines.push('<details><summary>Known limitations</summary>', '')
      for (const item of limited) {
        lines.push(`**\`${item.id}\`**`, '')
        for (const limitation of item.known_limitations) lines.push(`- ${limitation}`)
        lines.push('')
      }
      lines.push('</details>', '')
    }
  }

  const content = `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`
  const existing = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : null

  if (existing === content) {
    if (!check) process.stdout.write('status: up to date\n')
    return
  }
  if (check) {
    process.stderr.write('watch: docs/implementation-status.md is stale\n')
    process.stderr.write('watch: run `node scripts/gen-status.mjs` and commit the result\n')
    process.exit(1)
  }
  writeFileSync(OUTPUT, content)
  process.stdout.write(
    `wrote docs/implementation-status.md — ${String(ledger.items.length)} subsystems\n`
    + Object.entries(counts).sort()
      .map(([status, count]) => `  ${status.padEnd(18)} ${String(count)}\n`).join(''),
  )
}

main()
